### ISSUE TITLE
E-Ink theme

### ISSUE THREAD

**Issue by RudyAlbertoAcostaMarmalade** [Kareadita/Themes#17]
Hi Thanks for building such a fantastic application.  

I have just tried applying the E-Ink theme and noticed that the 'hover' text in menus is not visible - I presume because the font is set to white?  I'm using MS Edge on both my eBook reader and PC and can replicate on both.  Should I be looking for another setting elsewhere to adjust the menu font?

Thanks again

**Comment by majora2007** [comment]
If you are able, you can do a little sleuthing with your browser and see if you can identify the hover css property and adjust it and raise a PR. 

If there isn't one, please  give me information around the css class and an image (doesn't have to be on the theme) and I can add a new css property to help target that.
