### ISSUE TITLE
[E-ink] Low contrast on setting and certain pages

### ISSUE THREAD

**Issue by Rivers47** [Kareadita/Themes#24]
Some texts have very low contrast with its background, which makes it completely invisible on e-ink devices.

1. Click on the user icon at the top-right corner on mobile screen (you can also manually resize the browser window to a vertical shape for this layout to trigger on desktop) 
<img width="498" alt="image" src="https://github.com/user-attachments/assets/20d2f840-6eda-4eae-b55e-fbe9d2afe4cf">

2. Most setting pages from the hamburger menu, for example: (the description text are completely invisible)
<img width="1654" alt="image" src="https://github.com/user-attachments/assets/c92553ce-0fba-41bd-8e72-39fa69cee82e">

I'd love to help but I don't know how to find which variable controls which part of the interface...
So far I only found --setting-header-text-color should be set.

**Comment by majora2007** [comment]
If you inspect Element in your browser dev tools, you can identify the css variable for each item. 

For those navigation options, you do need to be on mobile (or a mobile device viewport) to trigger that screen.

**Comment by therobbiedavis** [comment]
There's also this resource: https://wiki.kavitareader.com/guides/themes#available-css-variables

**Comment by Rivers47** [comment]
> For those navigation options, you do need to be on mobile (or a mobile device viewport) to trigger that screen.

Sorry if I wasn't being clear,
If you narrow your browser window until your username at the top right corner disappear and only a user icon is there. You can then click the icon to view that panel.
